---
#------All
- hosts: all
  become: true
  roles:
    - update
    - unarchive
    - java

#------Bastion
- hosts: local
  connection: local
  become: true
  roles:
    - gitlab
    - jenkins
    - terraform

#------Sonar
- hosts: sonar
  become: true
  roles:
    - sonar

